require("dotenv").config();
const express=require("express"), helmet=require("helmet"), cookieParser=require("cookie-parser"), bcrypt=require("bcryptjs"), jwt=require("jsonwebtoken"), rateLimit=require("express-rate-limit"), Database=require("better-sqlite3");
const path=require("path");
const app=express(), db=new Database("ghar-ka-khana.db");
const PORT=process.env.PORT||3000, SECRET=process.env.JWT_SECRET;
if(!SECRET) console.warn("Set JWT_SECRET in .env before production use.");
app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:"200kb"}));app.use(cookieParser());app.use(express.static(path.join(__dirname,"public")));
db.pragma("journal_mode = WAL");
db.exec(`
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY, name TEXT NOT NULL, phone TEXT UNIQUE NOT NULL, email TEXT UNIQUE, password_hash TEXT NOT NULL, address TEXT DEFAULT '', role TEXT NOT NULL DEFAULT 'customer', created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS menu(id INTEGER PRIMARY KEY, name TEXT NOT NULL, description TEXT DEFAULT '', category TEXT NOT NULL, price INTEGER NOT NULL CHECK(price>0), image TEXT DEFAULT '', available INTEGER NOT NULL DEFAULT 1, created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), total INTEGER NOT NULL, address TEXT NOT NULL, notes TEXT DEFAULT '', status TEXT NOT NULL DEFAULT 'Received', created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS order_items(id INTEGER PRIMARY KEY, order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE, menu_id INTEGER, item_name TEXT NOT NULL, unit_price INTEGER NOT NULL, quantity INTEGER NOT NULL);
`);
// Create/update the owner account from environment variables on startup when configured.
if(process.env.ADMIN_PHONE && process.env.ADMIN_PASSWORD){
 const existing=db.prepare("SELECT id FROM users WHERE phone=?").get(process.env.ADMIN_PHONE);
 if(!existing){db.prepare("INSERT INTO users(name,phone,email,password_hash,role) VALUES(?,?,?,?,?)").run(process.env.ADMIN_NAME||"Ghar ka Khana Owner",process.env.ADMIN_PHONE,process.env.ADMIN_EMAIL||null,bcrypt.hashSync(process.env.ADMIN_PASSWORD,12),"admin");}
}
const count=db.prepare("SELECT COUNT(*) n FROM menu").get().n;
if(!count){const ins=db.prepare("INSERT INTO menu(name,description,category,price,image) VALUES(?,?,?,?,?)");[
["Paneer Makhani","Soft paneer in a rich tomato gravy","Main Course",160,""],["Matar Paneer","Paneer and peas in homestyle masala","Main Course",150,""],["Aloo Do Pyaza","Potatoes with onions and aromatic spices","Main Course",150,""],["Daal Fry","Comforting lentils finished with tadka","Main Course",120,""],["Aloo Paratha","Golden paratha stuffed with spiced potato","Parathas",60,""],["Paneer Paratha","Flaky paratha with savoury paneer filling","Parathas",80,""],["Pav Bhaji","Spiced vegetable mash with pav","Snacks",120,""],["Samosa","Crisp pastry with potato filling","Snacks",25,""],["Poha","Light flattened rice with peanuts and herbs","Breakfast",90,""]
].forEach(x=>ins.run(...x))}
function tokenFor(user){return jwt.sign({id:user.id,role:user.role},SECRET||"dev-only-change-me",{expiresIn:"7d"})}
function auth(req,res,next){try{const t=req.cookies.gkk_token||((req.headers.authorization||"").startsWith("Bearer ")?req.headers.authorization.slice(7):null);if(!t)throw Error();req.user=jwt.verify(t,SECRET||"dev-only-change-me");next()}catch(e){res.status(401).json({error:"Please sign in."})}}
function admin(req,res,next){if(req.user.role!=="admin")return res.status(403).json({error:"Owner access required."});next()}
const limiter=rateLimit({windowMs:15*60*1000,limit:100,standardHeaders:true,legacyHeaders:false});
app.use("/api",limiter);
app.post("/api/auth/register",(req,res)=>{const {name,phone,email,password,address=""}=req.body||{};if(!name||!phone||!password||String(password).length<8)return res.status(400).json({error:"Name, phone and password (8+ characters) are required."});try{const info=db.prepare("INSERT INTO users(name,phone,email,password_hash,address) VALUES(?,?,?,?,?)").run(name.trim(),phone.trim(),email||null,bcrypt.hashSync(password,12),address);const u=db.prepare("SELECT id,name,phone,email,address,role FROM users WHERE id=?").get(info.lastInsertRowid);res.cookie("gkk_token",tokenFor(u),{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",maxAge:7*864e5});res.json({user:u})}catch(e){res.status(409).json({error:"Phone or email already registered."})}});
app.post("/api/auth/login",(req,res)=>{const {phone,password}=req.body||{};const u=db.prepare("SELECT * FROM users WHERE phone=?").get(phone||"");if(!u||!bcrypt.compareSync(password||"",u.password_hash))return res.status(401).json({error:"Invalid phone or password."});const safe={id:u.id,name:u.name,phone:u.phone,email:u.email,address:u.address,role:u.role};res.cookie("gkk_token",tokenFor(safe),{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",maxAge:7*864e5});res.json({user:safe})});
app.post("/api/auth/logout",(req,res)=>res.clearCookie("gkk_token").json({ok:true}));
app.get("/api/auth/me",auth,(req,res)=>res.json({user:db.prepare("SELECT id,name,phone,email,address,role FROM users WHERE id=?").get(req.user.id)}));
app.get("/api/menu",(req,res)=>res.json(db.prepare("SELECT id,name,description,category,price,image,available FROM menu WHERE available=1 ORDER BY category,name").all()));
app.get("/api/admin/menu",auth,admin,(req,res)=>res.json(db.prepare("SELECT id,name,description,category,price,image,available FROM menu ORDER BY category,name").all()));
app.post("/api/menu",auth,admin,(req,res)=>{const {name,description="",category,price,image=""}=req.body||{};if(!name||!category||!Number.isInteger(Number(price))||Number(price)<1)return res.status(400).json({error:"Valid name, category and whole-number price required."});const r=db.prepare("INSERT INTO menu(name,description,category,price,image) VALUES(?,?,?,?,?)").run(name,description,category,Number(price),image);res.status(201).json(db.prepare("SELECT * FROM menu WHERE id=?").get(r.lastInsertRowid))});
app.patch("/api/menu/:id",auth,admin,(req,res)=>{const old=db.prepare("SELECT * FROM menu WHERE id=?").get(req.params.id);if(!old)return res.status(404).json({error:"Dish not found."});const d={...old,...req.body};db.prepare("UPDATE menu SET name=?,description=?,category=?,price=?,image=?,available=? WHERE id=?").run(d.name,d.description,d.category,Number(d.price),d.image,d.available?1:0,old.id);res.json(db.prepare("SELECT * FROM menu WHERE id=?").get(old.id))});
app.delete("/api/menu/:id",auth,admin,(req,res)=>{db.prepare("UPDATE menu SET available=0 WHERE id=?").run(req.params.id);res.json({ok:true})});
app.post("/api/orders",auth,(req,res)=>{const {items,address,notes=""}=req.body||{};if(!Array.isArray(items)||!items.length||!address)return res.status(400).json({error:"Cart and delivery address are required."});let total=0,validated=[];for(const it of items){const d=db.prepare("SELECT id,name,price FROM menu WHERE id=? AND available=1").get(Number(it.menuId));const q=Number(it.quantity);if(!d||!Number.isInteger(q)||q<1||q>50)return res.status(400).json({error:"Invalid cart item."});total+=d.price*q;validated.push({...d,quantity:q})}const create=db.transaction(()=>{const r=db.prepare("INSERT INTO orders(user_id,total,address,notes) VALUES(?,?,?,?)").run(req.user.id,total,address,notes);const ins=db.prepare("INSERT INTO order_items(order_id,menu_id,item_name,unit_price,quantity) VALUES(?,?,?,?,?)");validated.forEach(x=>ins.run(r.lastInsertRowid,x.id,x.name,x.price,x.quantity));return r.lastInsertRowid});const id=create();const order=readOrder(id);notifyWhatsApp(order).catch(e=>console.error("WhatsApp notification failed:",e.message));res.status(201).json(order)});
function readOrder(id){const o=db.prepare("SELECT o.*,u.name customer_name,u.phone customer_phone FROM orders o JOIN users u ON u.id=o.user_id WHERE o.id=?").get(id);if(!o)return null;o.items=db.prepare("SELECT item_name name,unit_price price,quantity FROM order_items WHERE order_id=?").all(id);return o}
app.get("/api/orders/mine",auth,(req,res)=>res.json(db.prepare("SELECT id,total,address,status,created_at FROM orders WHERE user_id=? ORDER BY id DESC").all(req.user.id)));
app.get("/api/admin/orders",auth,admin,(req,res)=>res.json(db.prepare("SELECT id FROM orders ORDER BY id DESC").all().map(x=>readOrder(x.id))));
app.patch("/api/admin/orders/:id",auth,admin,(req,res)=>{const allowed=["Received","Preparing","Ready","Out for delivery","Delivered","Cancelled"];if(!allowed.includes(req.body.status))return res.status(400).json({error:"Invalid status."});const r=db.prepare("UPDATE orders SET status=? WHERE id=?").run(req.body.status,req.params.id);if(!r.changes)return res.status(404).json({error:"Order not found."});res.json(readOrder(req.params.id))});
async function notifyWhatsApp(o){const {WHATSAPP_TOKEN,WHATSAPP_PHONE_NUMBER_ID,WHATSAPP_TO_NUMBER,WHATSAPP_API_VERSION="v21.0"}=process.env;if(!WHATSAPP_TOKEN||!WHATSAPP_PHONE_NUMBER_ID||!WHATSAPP_TO_NUMBER)return;const body=`New Ghar ka Khana order #${o.id}\\nCustomer: ${o.customer_name} (${o.customer_phone})\\nItems: ${o.items.map(i=>`${i.name} x${i.quantity}`).join(", ")}\\nTotal: ₹${o.total}\\nAddress: ${o.address}`;const r=await fetch(`https://graph.facebook.com/${WHATSAPP_API_VERSION}/${WHATSAPP_PHONE_NUMBER_ID}/messages`,{method:"POST",headers:{"Authorization":`Bearer ${WHATSAPP_TOKEN}`,"Content-Type":"application/json"},body:JSON.stringify({messaging_product:"whatsapp",to:WHATSAPP_TO_NUMBER,type:"text",text:{body}})});if(!r.ok)throw Error(await r.text())}
app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));
app.listen(PORT,()=>console.log(`Ghar ka Khana running at http://localhost:${PORT}`));
